NUM_SMALL_CELLS = 5
MACRO_CELL_CAPACITY = 100.0

SMALL_CELL_ACTIVE_POWER = 6.0
SMALL_CELL_LOAD_COEFF = 4.0
SMALL_CELL_SLEEP_POWER = 0.5
MACRO_CELL_BASE_POWER = 40.0
MACRO_CELL_LOAD_COEFF = 8.0

TRAFFIC_PEAK_HOUR = 14.0
TRAFFIC_BASE_LOAD = 5.0
TRAFFIC_AMPLITUDE = 15.0
TRAFFIC_NOISE_STD = 2.0

QOS_PENALTY_WEIGHT = 50.0
ENERGY_REWARD_SCALE = 0.1

STEPS_PER_EPISODE = 24
NUM_EPISODES = 800

LEARNING_RATE = 0.1
DISCOUNT_FACTOR = 0.95
EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY = 0.997

TRAFFIC_BINS = 3
TIME_BINS = 6
